/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMailSendRouteImport } from './routes/api/mail-send'
import { Route as ApiMailAttachmentRouteImport } from './routes/api/mail-attachment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicHooksMailSyncTickRouteImport } from './routes/api/public/hooks/mail-sync-tick'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailSendRoute = ApiMailSendRouteImport.update({
  id: '/api/mail-send',
  path: '/api/mail-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailAttachmentRoute = ApiMailAttachmentRouteImport.update({
  id: '/api/mail-attachment',
  path: '/api/mail-attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksMailSyncTickRoute =
  ApiPublicHooksMailSyncTickRouteImport.update({
    id: '/api/public/hooks/mail-sync-tick',
    path: '/api/public/hooks/mail-sync-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/mail-attachment': typeof ApiMailAttachmentRoute
  '/api/mail-send': typeof ApiMailSendRoute
  '/api/public/hooks/mail-sync-tick': typeof ApiPublicHooksMailSyncTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/mail-attachment': typeof ApiMailAttachmentRoute
  '/api/mail-send': typeof ApiMailSendRoute
  '/api/public/hooks/mail-sync-tick': typeof ApiPublicHooksMailSyncTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/company': typeof CompanyRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/mail-attachment': typeof ApiMailAttachmentRoute
  '/api/mail-send': typeof ApiMailSendRoute
  '/api/public/hooks/mail-sync-tick': typeof ApiPublicHooksMailSyncTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/login'
    | '/mail'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/mail-attachment'
    | '/api/mail-send'
    | '/api/public/hooks/mail-sync-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/login'
    | '/mail'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/mail-attachment'
    | '/api/mail-send'
    | '/api/public/hooks/mail-sync-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/company'
    | '/login'
    | '/mail'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/api/mail-attachment'
    | '/api/mail-send'
    | '/api/public/hooks/mail-sync-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiMailAttachmentRoute: typeof ApiMailAttachmentRoute
  ApiMailSendRoute: typeof ApiMailSendRoute
  ApiPublicHooksMailSyncTickRoute: typeof ApiPublicHooksMailSyncTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail-send': {
      id: '/api/mail-send'
      path: '/api/mail-send'
      fullPath: '/api/mail-send'
      preLoaderRoute: typeof ApiMailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail-attachment': {
      id: '/api/mail-attachment'
      path: '/api/mail-attachment'
      fullPath: '/api/mail-attachment'
      preLoaderRoute: typeof ApiMailAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/mail-sync-tick': {
      id: '/api/public/hooks/mail-sync-tick'
      path: '/api/public/hooks/mail-sync-tick'
      fullPath: '/api/public/hooks/mail-sync-tick'
      preLoaderRoute: typeof ApiPublicHooksMailSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CompanyRoute: CompanyRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiMailAttachmentRoute: ApiMailAttachmentRoute,
  ApiMailSendRoute: ApiMailSendRoute,
  ApiPublicHooksMailSyncTickRoute: ApiPublicHooksMailSyncTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
