-- Generate a fresh 256-bit master key and store it in Supabase Vault.
-- The key is generated by pgcrypto (server-side, never seen by any client).
DO $$
DECLARE
  v_key text;
BEGIN
  -- Skip if the key already exists (idempotent).
  IF NOT EXISTS (SELECT 1 FROM vault.secrets WHERE name = 'mail_credentials_master_key_v1') THEN
    -- 32 random bytes, base64-encoded.
    v_key := encode(extensions.gen_random_bytes(32), 'base64');
    PERFORM vault.create_secret(v_key, 'mail_credentials_master_key_v1',
      'AES-256-GCM master key for mail account credential ciphertext (version 1)');
  END IF;
END $$;

-- Add key_version column to mail_accounts for future rotation.
ALTER TABLE public.mail_accounts
  ADD COLUMN IF NOT EXISTS credentials_key_version integer,
  ADD COLUMN IF NOT EXISTS credentials_updated_at timestamptz;

COMMENT ON COLUMN public.mail_accounts.credentials_ciphertext IS
  'AES-256-GCM ciphertext of mail password. Format: v<version>:<b64nonce>:<b64tag>:<b64ciphertext>. NULL means credentials_pending (owner has never logged in).';
COMMENT ON COLUMN public.mail_accounts.credentials_key_version IS
  'Master key version used to encrypt credentials_ciphertext. NULL when ciphertext is NULL.';

-- Server-only RPC to fetch the master key by version.
-- SECURITY DEFINER runs as postgres, giving it access to vault schema.
-- EXECUTE is granted ONLY to service_role; anon/authenticated cannot call it.
CREATE OR REPLACE FUNCTION public.get_mail_credentials_master_key(p_version integer)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, vault, pg_temp
AS $$
DECLARE
  v_name text;
  v_key text;
BEGIN
  IF p_version IS NULL OR p_version < 1 OR p_version > 999 THEN
    RAISE EXCEPTION 'invalid key version' USING ERRCODE = '22023';
  END IF;
  v_name := 'mail_credentials_master_key_v' || p_version::text;
  SELECT decrypted_secret INTO v_key
    FROM vault.decrypted_secrets
   WHERE name = v_name
   LIMIT 1;
  IF v_key IS NULL THEN
    RAISE EXCEPTION 'mail credentials master key version % not found', p_version USING ERRCODE = '42704';
  END IF;
  RETURN v_key;
END;
$$;

-- Lock down: no anon/authenticated/public access.
REVOKE ALL ON FUNCTION public.get_mail_credentials_master_key(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_mail_credentials_master_key(integer) FROM anon;
REVOKE ALL ON FUNCTION public.get_mail_credentials_master_key(integer) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.get_mail_credentials_master_key(integer) TO service_role;
